name: publish ndk-pkg main

on:
  workflow_dispatch:

jobs:
  publish:

    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v4

      - run: |
          RELEASE_VERSION="$(./ndk-pkg --version)"

          install -d "ndk-pkg-$RELEASE_VERSION/bin/"
          install -d "ndk-pkg-$RELEASE_VERSION/share/zsh/vendor-completions/"

          cp ndk-pkg "ndk-pkg-$RELEASE_VERSION/bin/ndk-pkg"
          cp ndk-pkg-zsh-completion "ndk-pkg-$RELEASE_VERSION/share/zsh/vendor-completions/_ndk-pkg"

          RELEASE_FILE_NAME="ndk-pkg-$RELEASE_VERSION.tar.gz"

          tar zvcf "$RELEASE_FILE_NAME" "ndk-pkg-$RELEASE_VERSION"

          SHA256SUM="$(sha256sum "$RELEASE_FILE_NAME")"

          cat > notes.md <<EOF
          sha256sum:
          \`\`\`
          $SHA256SUM
          \`\`\`
          EOF

          gh release create "$RELEASE_VERSION" "$RELEASE_FILE_NAME" --title "$RELEASE_VERSION" --notes-file notes.md
